# Generated by Django 5.2.6 on 2025-09-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('enterprise', 'Enterprise'), ('admin', 'Admin')], default='free', max_length=20),
        ),
    ]
