# Generated by Django 5.2.6 on 2025-09-18 13:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Trip title must be at least 3 characters long')])),
                ('destination', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(3, 'Destination must be at least 3 characters long')])),
                ('departure_date', models.DateTimeField()),
                ('meeting_point', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(5, 'Meeting point must be at least 5 characters long')])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Description must be at least 10 characters long')])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='published', max_length=20)),
                ('max_participants', models.PositiveIntegerField(default=20, help_text='Maximum number of participants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_duration', models.CharField(blank=True, help_text="e.g., '2 days', '6 hours'", max_length=100)),
                ('estimated_distance', models.CharField(blank=True, help_text="e.g., '500 miles', '800 km'", max_length=100)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='easy', max_length=20)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_to_all', models.BooleanField(default=False)),
                ('eligible_brands', models.ManyToManyField(blank=True, related_name='eligible_trips', to='cars.carbrand')),
                ('eligible_models', models.ManyToManyField(blank=True, related_name='eligible_trips', to='cars.carmodel')),
                ('eligible_types', models.ManyToManyField(blank=True, related_name='eligible_trips', to='cars.cartype')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='roadtrips.roadtrip')),
            ],
            options={
                'verbose_name_plural': 'Trip Eligibilities',
            },
        ),
        migrations.CreateModel(
            name='TripNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_trip', 'New Trip Available'), ('trip_updated', 'Trip Updated'), ('trip_cancelled', 'Trip Cancelled'), ('join_request', 'Join Request'), ('request_approved', 'Request Approved'), ('request_declined', 'Request Declined'), ('participant_joined', 'New Participant'), ('participant_left', 'Participant Left'), ('trip_reminder', 'Trip Reminder')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='roadtrips.roadtrip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, help_text='Message from participant')),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='roadtrips.roadtrip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='roadtrip',
            index=models.Index(fields=['departure_date'], name='roadtrips_r_departu_401810_idx'),
        ),
        migrations.AddIndex(
            model_name='roadtrip',
            index=models.Index(fields=['status'], name='roadtrips_r_status_13752e_idx'),
        ),
        migrations.AddIndex(
            model_name='roadtrip',
            index=models.Index(fields=['organizer'], name='roadtrips_r_organiz_97155a_idx'),
        ),
        migrations.AddIndex(
            model_name='tripnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='roadtrips_t_recipie_41f21e_idx'),
        ),
        migrations.AddIndex(
            model_name='tripnotification',
            index=models.Index(fields=['created_at'], name='roadtrips_t_created_f77230_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripparticipant',
            unique_together={('trip', 'user')},
        ),
    ]
